name: Continuous Deployment

on:
  push:
    branches:
      - "Mike's-Frontend"
jobs:
  push_to_registry:
    name: Deploying Docker Image to Container Registry
    runs-on: ubuntu-latest
    steps:
      # resource: https://github.com/actions/checkout 
      - name: Pull Latest Code From Github Repo
        uses: actions/checkout@v4

      - name: Set up Buildx environment
        uses: docker/setup-buildx-action@v3
      # resource: https://github.com/docker/login-action?tab=readme-ov-file
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MIKES_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # resource: https://github.com/docker/build-push-action 
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: mylee2002/pokemon-tb:latest


    